name: dart_pre_commit
description: A small collection of pre commit hooks to format and lint dart code
version: 6.0.1
homepage: https://github.com/Skycoder42/dart_pre_commit

environment:
  sdk: ^3.10.0

platforms:
  linux:
  macos:
  windows:

executables:
  dart_pre_commit: dart_pre_commit

dependencies:
  analyzer: ^8.4.0
  args: ^2.7.0
  checked_yaml: ^2.0.4
  console: ^4.1.0
  convert: ^3.1.2
  crypto: ^3.0.7
  freezed_annotation: ^3.1.0
  get_it: ^9.0.5
  injectable: ^2.6.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: ^1.17.0
  path: ^1.9.1
  pub_semver: ^2.2.0
  pubspec_parse: ^1.5.0
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.10.3
  coverage: ^1.15.0
  custom_lint: ^0.8.1
  dart_test_tools: ^6.2.3+1
  freezed: ^3.2.3
  injectable_generator: ^2.9.1
  json_serializable: ^6.11.1
  mocktail: ^1.0.4
  test: ^1.26.3
  yaml_edit: ^2.2.2

cider:
  link_template:
    tag: https://github.com/Skycoder42/dart_pre_commit/releases/tag/v%tag%
    diff: https://github.com/Skycoder42/dart_pre_commit/compare/v%from%...v%to%

dart_pre_commit:
  pull-up-dependencies:
    allowed:
      - analyzer
      - meta
      - path
